### ISSUE TITLE
duplex-tools

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#150]
* link to support ticket: [#2023033060002727](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=116051)
* website: https://github.com/nanoporetech/duplex-tools
* installation docs: https://github.com/nanoporetech/duplex-tools#installation
* toolchain: `foss/2022b`
* easyblock to use: `PythonBundle`
* required dependencies:
  * *(see existing easyconfigs)*
* notes:
  * update of `duplex-tools-0.3.1-foss-2022a.eb`
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
@PetrKralCZ https://github.com/easybuilders/easybuild-easyconfigs/pull/18154 merged, so ready for cleanup & closing...

**Comment by laraPPr** [comment]
User is reporting that the software is crashing due to a bug in pyarrow. 
- [#2023121560000553](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=142185)
```
d=00_raw/C1
sample=$(basename $d)
module load duplex-tools/0.3.3-foss-2022a
duplex_tools split_pairs 01_basecalling/${sample}_unmapped_reads_with_moves.bam $d 01_basecalling/${sample}_splitduplex
 
Throws the following error:
[vsc45601@node3308 231214_data_CGT_reruntest]$ duplex_tools split_pairs 01_basecalling/${sample}_unmapped_reads_with_moves.bam $d 01_basecalling/$
{sample}_splitduplex                                                                                                                             
[10:35:31 - SplitPairs] Find split locations.                                                                                                    
[10:35:31 - SplitPairs] Self-align reads from: 01_basecalling/C1_unmapped_reads_with_moves.bam                                                   
[10:35:35 - SplitPairs] Split/Processed reads:7/5000 (0.14%)                                                                                     
[10:35:39 - SplitPairs] Split/Processed reads:9/10000 (0.09%)                                                                                    
[10:35:42 - SplitPairs] Split/Processed reads:12/15000 (0.08%)
….
[10:38:43 - SplitPairs] Split/Processed reads:318/267409 (0.12%)
[10:38:43 - SplitPairs] Finished finding breakpoints.
[10:38:43 - SplitPairs] Splitting 318 reads from: 00_raw/C1 into 01_basecalling/C1_splitduplex                                                  
[10:38:43 - SplitPairs] Splitting 00_raw/C1/ASL706_pass_dc4775e7_3f77f8a1_159.pod5                                                              
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/apps/gent/RHEL8/cascadelake-ib/software/duplex-tools/0.3.3-foss-2022a/bin/duplex_tools", line 8, in <module>                           
    sys.exit(main())
  File "/apps/gent/RHEL8/cascadelake-ib/software/duplex-tools/0.3.3-foss-2022a/lib/python3.10/site-packages/duplex_tools/__init__.py", line 39, in main
    args.func(args)
  File "/apps/gent/RHEL8/cascadelake-ib/software/duplex-tools/0.3.3-foss-2022a/lib/python3.10/site-packages/duplex_tools/split_pairs.py", line 134, in main
    split_pairs(
  File "/apps/gent/RHEL8/cascadelake-ib/software/duplex-tools/0.3.3-foss-2022a/lib/python3.10/site-packages/duplex_tools/split_pairs.py", line 53, in split_pairs
    _ = split_pod5(
  File "/apps/gent/RHEL8/cascadelake-ib/software/duplex-tools/0.3.3-foss-2022a/lib/python3.10/site-packages/duplex_tools/split_pairs_steps.py", line 135, in split_pod5
    read_obj = read.to_read()
  File "/apps/gent/RHEL8/cascadelake-ib/software/pod5-file-format/0.1.8-foss-2022a/lib/python3.10/site-packages/pod5/reader.py", line 432, in to_read
    read_id=self.read_id,
  File "/apps/gent/RHEL8/cascadelake-ib/software/pod5-file-format/0.1.8-foss-2022a/lib/python3.10/site-packages/pod5/reader.py", line 121, in read_id
    return UUID(bytes=self._batch.columns.read_id[self._row].as_py())
  File "/apps/gent/RHEL8/cascadelake-ib/software/pod5-file-format/0.1.8-foss-2022a/lib/python3.10/site-packages/pod5/reader.py", line 464, in columns
    *[
  File "/apps/gent/RHEL8/cascadelake-ib/software/pod5-file-format/0.1.8-foss-2022a/lib/python3.10/site-packages/pod5/reader.py", line 465, in <listcomp>
    self._batch.column(name)
  File "pyarrow/table.pxi", line 1890, in pyarrow.lib.RecordBatch.column
  File "pyarrow/table.pxi", line 1906, in pyarrow.lib.RecordBatch._column                                                                       
  File "pyarrow/public-api.pxi", line 200, in pyarrow.lib.pyarrow_wrap_array                                                                    
  File "pyarrow/array.pxi", line 2802, in pyarrow.lib.get_array_class_from_type                                                                 
AttributeError: 'pyarrow.lib.BaseExtensionType' object has no attribute '__arrow_ext_class__'. Did you mean: '_columns'?   
 
```

**Comment by boegel** [comment]
see https://github.com/apache/arrow/pull/33802

**Comment by boegel** [comment]
We can extract a small patch from https://github.com/apache/arrow/pull/33802, that fixes stuff in `python/pyarrow/types.pxi`

to reproduce
```
$ python -c 'from pyarrow.lib import BaseExtensionType; print(BaseExtensionType.__arrow_ext_class__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: type object 'pyarrow.lib.BaseExtensionType' has no attribute '__arrow_ext_class__'
```

**Comment by PetrKralCZ** [comment]
Arrow bug fix
- https://github.com/easybuilders/easybuild-easyconfigs/pull/19532

**Comment by boegel** [comment]
I've reinstalled the `Arrow/8.*` and `Arrow/11.*` on all our systems with the fix from https://github.com/easybuilders/easybuild-easyconfigs/pull/19532

@laraPPr Can you ask the researcher to test again?

**Comment by boegel** [comment]
Asked the researcher to test again, closing until further notice...
