### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#305]
* link to support ticket: [#2024030660000381](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=149557)
* website: https://yoseflab.github.io/Compass/
* installation docs: https://yoseflab.github.io/Compass/install.html
* toolchain: `foss/2023a`
* easyblock to use: `PythonPackage`
* required dependencies:
  * [x] numpy
* optional dependencies:
  * [x] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
@pavelToman I'm looking into getting `CPLEX-22.1.1-GCCcore-12.3.0.eb` to work, and I thought it would be possible to convince CPLEX 22.1.1 to use Python 3.11, but that doesn't seem to be working.

I tried adding this to the easyconfig:
```python
installopts = " && cp -a %(installdir)s/cplex/python/3.10 %(installdir)s/cplex/python/3.11 && "
installopts += "sed -i 's/3.10/3.11/g' %(installdir)s/cplex/python/3.11/x86-64_linux/setup.py && "
installopts += "cd %(installdir)s/cplex/python/3.11/x86-64_linux/cplex/_internal && "
installopts += "ln -s py310_cplex%(v)s.so py311_cplex%(v)s.so" % {'v': version.replace('.', '')}
```
(this requires the enhanced CPLEX easyblock in https://github.com/easybuilders/easybuild-easyblocks/pull/3317 to pick up `installopts`)

That doesn't fully work however, because the `import cplex` in sanity check fails with:
```
== 2024-05-02 19:52:19,793 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): Sanity check failed: sanity check command python -c 'import cplex' exited with code 1 (output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/software/CPLEX/22.1.1-GCCcore-12.3.0/lib/python3.11/site-packages/cplex/__init__.py", line 44, in <module>
    from .aborter import Aborter
  File "/software/CPLEX/22.1.1-GCCcore-12.3.0/lib/python3.11/site-packages/cplex/aborter.py", line 13, in <module>
    from ._internal import _procedural as _proc
  File "/software/CPLEX/22.1.1-GCCcore-12.3.0/lib/python3.11/site-packages/cplex/_internal/__init__.py", line 20, in <module>
    from . import _list_array_utils
  File "/software/CPLEX/22.1.1-GCCcore-12.3.0/lib/python3.11/site-packages/cplex/_internal/_list_array_utils.py", line 14, in <module>
    from . import _pycplex as CPX
  File "/software/CPLEX/22.1.1-GCCcore-12.3.0/lib/python3.11/site-packages/cplex/_internal/_pycplex.py", line 13, in <module>
    from . import _pycplex_platform
  File "/usoftware/CPLEX/22.1.1-GCCcore-12.3.0/lib/python3.11/site-packages/cplex/_internal/_pycplex_platform.py", line 30, in <module>
    from cplex._internal.py311_cplex2211 import *
ImportError: dynamic module does not define module export function (PyInit_py311_cplex2211)
```

That basically means we're stuck to Python 3.10 for now for CPLEX, which probably means that we should stick with `foss/2022b` for Compass as well?

**Comment by pavelToman** [comment]
Yes, it seems so. For `foss/2022b` there is missing dependencies `python-libsbml` and `anndata`. I am gonna create them.

**Comment by pavelToman** [comment]
Draft for foss/2022b - needs to be updated as soon as CPLEX for GCCcore 12.2.0 is ready. It should possible to build it even without CPLEX.
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20499

**Comment by pavelToman** [comment]
Working version for foss/2021b:
- https://github.com/easybuilders/easybuild-easyconfigs/pull/20500

**Comment by pavelToman** [comment]
There seems to be a problem with CPLEX-22.1.1 for GCCcore/12.2.0 either for GCCcore/11.3.0 because of zlib version. For 12.2.0 and 11.3.0 the python version has zlib v1.2.12. Seems it is same problem as with other IBM sw: https://www.ibm.com/support/pages/aix-open-source-semeru-javazipexception-invalid-entry-crc-errors-after-zlib-updates

There are some logs from installation:
```
        Install Complete
        ----------------

        The installation of IBM ILOG CPLEX Optimization Studio 22.1.1 is complete, but
        some errors occurred during the install.
           Please see the installation log for details in:  /kyukon/scratch/gent/vo/00
        1/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CPLEX/22.1.1-GCCcore
        -12.2.0/Uninstall/Logs/.
           Press "ENTER" to quit the installer.

        PRESS <ENTER> TO EXIT THE INSTALLER:  (at easybuild/easybuild-framework/easybuild/tools/run.py:682 in parse_cmd_output)
        == 2024-05-06 17:07:56,584 build_log.py:267 INFO ... (took 2 mins 41 secs)
        == 2024-05-06 17:07:56,584 filetools.py:2013 INFO Removing lock /scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/.locks/_scratch_gent_vo_001_gvo00117_easybuild_RHEL8_cascadelake-ampere-ib_software_CPLEX_22.1.1-GCCcore-12.2.0.lock...
        == 2024-05-06 17:07:56,586 filetools.py:383 INFO Path /scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/.locks/_scratch_gent_vo_001_gvo00117_easybuild_RHEL8_cascadelake-ampere-ib_software_CPLEX_22.1.1-GCCcore-12.2.0.lock successfully removed.
        == 2024-05-06 17:07:56,586 filetools.py:2017 INFO Lock removed: /scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/.locks/_scratch_gent_vo_001_gvo00117_easybuild_RHEL8_cascadelake-ampere-ib_software_CPLEX_22.1.1-GCCcore-12.2.0.lock
        == 2024-05-06 17:07:56,586 easyblock.py:4291 WARNING build failed (first 300 chars): cmd "/tmp/vsc47063/easybuild/build/CPLEX/22.1.1/GCCcore-12.2.0/cplex_studio2211.linux_x86_64.bin -i console" exited with exit code 1 and output:
        Preparing to install
        Extracting the JRE from the installer archive...
        Unpacking the JRE...
        Extracting the installation resources from the installer archive
```

```
        Installation: Successful with errors.
        25163 Successes
        0 Warnings
        6 NonFatalErrors
        0 FatalErrors
```

```
        Install File:
        kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CPLEX/22.1.1-GCCcore-12.2.0/doc/html/en-US/OPL_Studio/refoplide/images
        /ast_find_refs_to_opl.png
                          Status: ERROR
                          Additional Notes: ERROR - Flexeraak8: invalid entry CRC (expected 0xaa7ae38a but got 0xfdacad95)
        ...
        Install File:             /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CPLEX/22.1.1-GCCcore-12.2.0/doc/html/
        en-US/refcallablelibrary/groups/homepagemodelasstcallback.html
                          Status: ERROR
                          Additional Notes: ERROR - Flexeraak8: invalid entry CRC (expected 0x3eea0b9 but got 0x5fd09566)
        ...
        Install File:             /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CPLEX/22.1.1-GCCcore-12.2.0/doc/html/
        en-US/refdotnetopl/html/Methods_T_ILOG_CP_CP.htm
                          Status: ERROR
                          Additional Notes: ERROR - Flexeraak8: invalid entry CRC (expected 0x3dc974d8 but got 0x5acf1094)
        ...
        Install File:             /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CPLEX/22.1.1-GCCcore-12.2.0/doc/html/
        en-US/refpythoncplex/html/class_hierarchy_for_qp_alg_con.gif
                          Status: ERROR
                          Additional Notes: ERROR - Flexeraak8: invalid entry CRC (expected 0x178a383f but got 0x3fa6c427)
        ...
        Install File:             /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CPLEX/22.1.1-GCCcore-12.2.0
        /opl/ant/bin/lcp.bat
                          Status: ERROR
                          Additional Notes: ERROR - Flexeraak8: invalid entry CRC (expected 0x2b4f5f15 but got 0xf061df8e)
        ...
        Install File:             /kyukon/scratch/gent/vo/001/gvo00117/easybuild/RHEL8/cascadelake-ampere-ib/software/CPLEX/22.1.1-GCCcore-12.2.0
        /opl/oplide/plugins/ilog.odms.cplex.help_22.1.1.202211281837/META-INF/COMPAGNI.RSA
                          Status: ERROR
                          Additional Notes: ERROR - Flexeraak8: invalid entry CRC (expected 0xebdc8d10 but got 0x55fa6010)
```
