### ISSUE TITLE
Faiss

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#364]
* link to support ticket: [#2024062760000479](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=160578)
* website: https://github.com/facebookresearch/faiss
* installation docs: https://github.com/facebookresearch/faiss/blob/main/INSTALL.md
* toolchain: `foss/2023a`
* easyblock to use: `CMakePythonPackage`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by laraPPr** [comment]
I had installed https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/f/Faiss/Faiss-1.7.4-foss-2023a-CUDA-12.1.1.eb but this config does not seem to work

when loading the faiss module you get the following error:
```
>>> import faiss

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/apps/gent/RHEL8/cascadelake-ampere-ib/software/Faiss/1.7.4-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/faiss/__init__.py", line 16, in <module>

    from .loader import *

  File "/apps/gent/RHEL8/cascadelake-ampere-ib/software/Faiss/1.7.4-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/faiss/loader.py", line 65, in <module>

    from .swigfaiss import *

  File "/apps/gent/RHEL8/cascadelake-ampere-ib/software/Faiss/1.7.4-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/faiss/swigfaiss.py", line 10, in <module>

    from . import _swigfaiss

ImportError: libfaiss_python_callbacks.so: cannot open shared object file: No such file or directory
```

**Comment by laraPPr** [comment]
https://github.com/facebookresearch/faiss/issues/2852

**Comment by laraPPr** [comment]
I could find the file but don't know why faiss can't `/apps/gent/RHEL8/cascadelake-ampere-ib/software/Faiss1.7.4-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/faiss/libfaiss_python_callbacks.so`

**Comment by laraPPr** [comment]
https://github.com/facebookresearch/faiss/pull/2062

**Comment by laraPPr** [comment]
Ah it is missing an underscore

**Comment by laraPPr** [comment]
in the easyconfig and the logs I can only find the correct one  https://github.com/easybuilders/easybuild-easyconfigs/blob/2e5ece977a93122f77b4898cb6e1969ecf8f2840/easybuild/easyconfigs/f/Faiss/Faiss-1.7.4-foss-2023a-CUDA-12.1.1.eb#L59C10-L59C41
but on in the filesystem is is not

**Comment by laraPPr** [comment]
Output strace it goes looking for `libfaiss_python_callbacks.so` in `software/Faiss/1.7.4-foss-2023a-CUDA-12.1.1/lib/libfaiss_python_callbacks.so` but not in `software/Faiss1.7.4-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/faiss/libfaiss_python_callbacks.so` where it actully is.  

`strace python -c 'import faiss'`

```
openat(AT_FDCWD, "/data/gent/vo/000/gvo00002/vsc46128/easybuild/RHEL8/cascadelake-ampere-ib/software/Faiss/1.7.4-foss-2023a-CUDA-12.1.1/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ampere-ib/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1/lib/python3.11/site-packages/torch/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/Z3/4.12.2-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/MPC/1.3.1-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/LibTIFF/4.5.0-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/libdeflate/1.18-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/zstd/1.5.5-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/lz4/1.9.4-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/jbigkit/2.1-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/libjpeg-turbo/2.1.5.1-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/FFmpeg/6.0-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/SDL2/2.28.2-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/FriBidi/1.0.12-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/X11/20230603-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/fontconfig/2.14.2-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/util-linux/2.39-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/freetype/2.13.0-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/Brotli/1.0.9-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/libpng/1.6.39-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/expat/2.5.0-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/x265/3.5-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/LAME/3.100-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/x264/20230226-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/MPFR/4.2.0-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/GMP/6.2.1-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/libyaml/0.2.5-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/numpy/core/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/protobuf/24.0-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/Abseil/20230125.3-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ampere-ib/software/NCCL/2.18.3-GCCcore-12.3.0-CUDA-12.1.1/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ampere-ib/software/magma/2.7.2-foss-2023a-CUDA-12.1.1/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ampere-ib/software/GDRCopy/2.3.1-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ampere-ib/software/cuDNN/8.9.2.26-CUDA-12.1.1/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/Python/3.11.3-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/libffi/3.4.4-GCCcore-12.3.0/lib64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/SQLite/3.42.0-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/Tcl/8.6.13-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/libreadline/8.2-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/ncurses/6.4-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/bzip2/1.0.8-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ampere-ib/software/CUDA/12.1.1/nvvm/lib64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ampere-ib/software/CUDA/12.1.1/extras/CUPTI/lib64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ampere-ib/software/CUDA/12.1.1/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/ScaLAPACK/2.2.0-gompi-2023a-fb/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/FFTW.MPI/3.3.10-gompi-2023a/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/FFTW/3.3.10-GCC-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/FlexiBLAS/3.3.1-GCC-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/OpenBLAS/0.3.23-GCC-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/OpenMPI/4.1.5-GCC-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/UCC/1.2.0-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/PMIx/4.2.4-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/UCX/1.14.1-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/libevent/2.1.12-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/OpenSSL/1.1/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/hwloc/2.9.1-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/libpciaccess/0.17-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/libxml2/2.11.4-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/XZ/5.4.2-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/numactl/2.0.16-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/binutils/2.40-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/zlib/1.2.13-GCCcore-12.3.0/lib/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/apps/gent/RHEL8/cascadelake-ib/software/GCCcore/12.3.0/lib64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3

fstat(3, {st_mode=S_IFREG|0644, st_size=53431, ...}) = 0

mmap(NULL, 53431, PROT_READ, MAP_PRIVATE, 3, 0) = 0x14605e506000

close(3)                                = 0

openat(AT_FDCWD, "/lib64/glibc-hwcaps/x86-64-v4/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/glibc-hwcaps/x86-64-v4", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/glibc-hwcaps/x86-64-v3/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/glibc-hwcaps/x86-64-v3", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/glibc-hwcaps/x86-64-v2/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/glibc-hwcaps/x86-64-v2", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/tls/haswell/avx512_1/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/tls/haswell/avx512_1/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/tls/haswell/avx512_1/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/tls/haswell/avx512_1", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/tls/haswell/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/tls/haswell/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/tls/haswell/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/tls/haswell", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/tls/avx512_1/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/tls/avx512_1/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/tls/avx512_1/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/tls/avx512_1", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/tls/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/tls/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/tls/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/tls", {st_mode=S_IFDIR|0555, st_size=4096, ...}) = 0

openat(AT_FDCWD, "/lib64/haswell/avx512_1/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/haswell/avx512_1/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/haswell/avx512_1/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/haswell/avx512_1", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/haswell/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/haswell/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/haswell/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/haswell", 0x7ffcaddac250)  = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/avx512_1/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/avx512_1/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/avx512_1/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/avx512_1", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64/x86_64", 0x7ffcaddac250)   = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/lib64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/lib64", {st_mode=S_IFDIR|0555, st_size=86016, ...}) = 0

openat(AT_FDCWD, "/usr/lib64/glibc-hwcaps/x86-64-v4/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/glibc-hwcaps/x86-64-v4", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/glibc-hwcaps/x86-64-v3/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/glibc-hwcaps/x86-64-v3", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/glibc-hwcaps/x86-64-v2/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/glibc-hwcaps/x86-64-v2", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/tls/haswell/avx512_1/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/tls/haswell/avx512_1/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/tls/haswell/avx512_1/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/tls/haswell/avx512_1", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/tls/haswell/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/tls/haswell/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/tls/haswell/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/tls/haswell", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/tls/avx512_1/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/tls/avx512_1/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/tls/avx512_1/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/tls/avx512_1", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/tls/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/tls/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/tls/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/tls", {st_mode=S_IFDIR|0555, st_size=4096, ...}) = 0

openat(AT_FDCWD, "/usr/lib64/haswell/avx512_1/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/haswell/avx512_1/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/haswell/avx512_1/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/haswell/avx512_1", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/haswell/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/haswell/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/haswell/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/haswell", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/avx512_1/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/avx512_1/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/avx512_1/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/avx512_1", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)

openat(AT_FDCWD, "/usr/lib64/x86_64/libfaiss_python_callbacks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

stat("/usr/lib64/x86_64", 0x7ffcaddac250) = -1 ENOENT (No such file or directory)
```

**Comment by laraPPr** [comment]
Have given the user a workaround for now to set an extra path in `LD_LIBRARY_PATH`

```
module load Faiss/1.7.4-foss-2023a-CUDA-12.1.1
export LD_LIBRARY_PATH=$EBROOTFAISS/lib/python3.11/site-packages/faiss:$LD_LIBRARY_PATH
```

**Comment by boegel** [comment]
The `import faiss` performed during the sanity check step passes, probably because the build directory is still present at that time.
This actually suggests that there's a bug in EasyBuild: we should rename the build directory when running the sanity check, to make sure that nothing in the sanity check relies on the build directory?

**Comment by boegel** [comment]
@laraPPr We could inject the missing path to `$LD_LIBRARY_PATH` in the module, by using

```python
modextrapaths = {'LD_LIBRARY_PATH': "lib/python%(pyshortver)s/site-packages/faiss"}
```

**Comment by laraPPr** [comment]
@Boegel Can you do a `--module-only` rebuild for Faiss so that the extra path gets added.

**Comment by boegel** [comment]
relevant PR for `$LD_LIBRARY_PATH` fix for Faiss:
* https://github.com/easybuilders/easybuild-easyconfigs/pull/21799

**Comment by boegel** [comment]
`Faiss/1.7.4-foss-2023a-CUDA-12.1.1` modules have been re-generated on all HPC-UGent Tier-2 GPU clusters, so closing...
