### ISSUE TITLE
wandb

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#49]
* link to support ticket: [#2022110960000685](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=100224)
* website: https://wandb.ai/site
* installation docs: https://docs.wandb.ai/quickstart
* toolchain: `foss/2021a`
* easyblock to use: `PythonBundle`
* required dependencies:
  * see https://github.com/wandb/wandb/blob/main/requirements.txt
* notes:
  * ...
* effort: *(TBD)*

**Comment by boegel** [comment]
This looked like a relatively easy update, but I ran into an installation error which I haven't been able to get back to yet; see draft easyconfig in [49_wandb](https://github.com/vscentrum/vsc-software-stack/tree/main/49_wandb)

**Comment by boegel** [comment]
Problems to fix is failing `import wandb` sanity check:

```
failing sanity check for 'wandb' extension: command "python -c "import wandb"" failed; output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/haswell-ib/software/wandb/0.13.5-GCC-11.2.0/lib/python3.9/site-packages/wandb/__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "/user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/haswell-ib/software/wandb/0.13.5-GCC-11.2.0/lib/python3.9/site-packages/wandb/sdk/__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "/user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/haswell-ib/software/wandb/0.13.5-GCC-11.2.0/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 30, in <module>
    from . import wandb_login, wandb_setup
  File "/user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/haswell-ib/software/wandb/0.13.5-GCC-11.2.0/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 25, in <module>
    from .wandb_settings import Settings, Source
  File "/user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/haswell-ib/software/wandb/0.13.5-GCC-11.2.0/lib/python3.9/site-packages/wandb/sdk/wandb_settings.py", line 39, in <module>
    from wandb.sdk.wandb_setup import _EarlyLogger
  File "/user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/haswell-ib/software/wandb/0.13.5-GCC-11.2.0/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 22, in <module>
    from . import wandb_manager, wandb_settings
  File "/user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/haswell-ib/software/wandb/0.13.5-GCC-11.2.0/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 14, in <module>
    from wandb.sdk.lib.proto_util import settings_dict_from_pbmap
  File "/user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/haswell-ib/software/wandb/0.13.5-GCC-11.2.0/lib/python3.9/site-packages/wandb/sdk/lib/proto_util.py", line 6, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/haswell-ib/software/wandb/0.13.5-GCC-11.2.0/lib/python3.9/site-packages/wandb/proto/wandb_internal_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_internal_pb2 import *
  File "/user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/haswell-ib/software/wandb/0.13.5-GCC-11.2.0/lib/python3.9/site-packages/wandb/proto/v3/wandb_internal_pb2.py", line 16, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "/user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/haswell-ib/software/wandb/0.13.5-GCC-11.2.0/lib/python3.9/site-packages/wandb/proto/wandb_base_pb2.py", line 6, in <module>
    from wandb.proto.v3.wandb_base_pb2 import *
  File "/user/gent/400/vsc40023/eb_arcaninescratch/RHEL8/haswell-ib/software/wandb/0.13.5-GCC-11.2.0/lib/python3.9/site-packages/wandb/proto/v3/wandb_base_pb2.py", line 21, in <module>
    __RECORDINFO = DESCRIPTOR.message_types_by_name['_RecordInfo']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name',  (at easybuild/framework/easyblock.py:3479 in _sanity_check_step)
```

Seems to correspond with https://github.com/protocolbuffers/protobuf/issues/10075, which implies that an update (or a fix) of `protobuf-python` is required?

**Comment by boegel** [comment]
PR merged
